@startuml "Overlays"

' WorkStarted
' WorkEnded
' Backgrounded
' Foregrounded

state ShowingNothing
state ShowingBusy
ShowingBusy : WorkStarted / IncrementWorkCount
ShowingBusy : WorkEnded [StackedWorkRemaining] / DecrementWorkCount

state ShowingPrivacy {
    state NoWork
    state DeferredWork
    DeferredWork : WorkStarted / IncrementWorkCount
    DeferredWork : WorkEnded [StackedWorkRemaining] / DecrementWorkCount

    [*] --> NoWork
    NoWork --> DeferredWork : WorkStarted /\nIncrementWorkCount
    DeferredWork --> NoWork : WorkEnded
}
state ShowingPrivacyOverBusy {
    state WorkUnderneath
    WorkUnderneath : WorkStarted / IncrementWorkCount
    WorkUnderneath : WorkEnded [StackedWorkRemaining] / DecrementWorkCount
    state NoLongerBusy

    [*] --> WorkUnderneath
    WorkUnderneath --> NoLongerBusy : WorkEnded
    NoLongerBusy --> WorkUnderneath : WorkStarted /\nIncrementWorkCount
}

[*] --> ShowingNothing

ShowingNothing --> ShowingBusy : WorkStarted /\nIncrementWorkCount\nShowBusyOverlay
ShowingBusy --> ShowingNothing : WorkEnded /\nPopOverlay

ShowingNothing --> ShowingPrivacy : Backgrounded /\nAddPrivacyOverlay
ShowingPrivacy --> ShowingNothing : Foregrounded /\nPopOverlay
DeferredWork --> ShowingBusy : Foregrounded /\nPopOverlay\nAddBusyOverlay

ShowingBusy --> ShowingPrivacyOverBusy : Backgrounded /\nAddPrivacyOverlay
ShowingPrivacyOverBusy --> ShowingBusy : Foregrounded /\nPopOverlay

NoLongerBusy --> ShowingNothing : Foregrounded /\nPopOverlay\nPopOverlay

@enduml